# Generated by Django 3.2.4 on 2021-06-25 05:45

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('draftwebivent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='course_yr_lvl',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interest',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Art', 'Art'), ('Business', 'Business'), ('Career', 'Career'), ('Design', 'Design'), ('Environment', 'Environment'), ('Gaming', 'Gaming'), ('Health', 'Health'), ('Leadership', 'Leadership'), ('Media', 'Media'), ('Politics', 'Politics'), ('Programming', 'Programming'), ('Technology', 'Technology')], default='', max_length=101),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='province',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.CharField(default='', max_length=250),
        ),
    ]
